Xcode bamboozled me
DeviesDevelopment/blog pull request #55
Opened 2022-09-05 13:57 UTC by omersimsek29

2022-09-05 14:16 UTC, BunnyFiscuit requested changes

2022-09-05 14:16 UTC, BunnyFiscuit commented on content/posts/2022-09-01_how-xcode-bamboozled-me.md
> +It's ten o'clock in the morning and I've just configurated and bumped the dependencies for my client's android application which they hadn't touched for over two years. Everything looked decent and w
- configurated -> configured
- I was now ready for their iOS application -> I was now ready to *further develop* their iOS application

2022-09-05 14:16 UTC, BunnyFiscuit commented on content/posts/2022-09-01_how-xcode-bamboozled-me.md
> +Reading this, my first instinct was to search this up on the good old browser. I felt safe and relieved reading posts and threads about other developers who also had gotten the same error message thi
Börja listan istället med

> The most common solutions suggested:

2022-09-05 14:16 UTC, BunnyFiscuit commented on content/posts/2022-09-01_how-xcode-bamboozled-me.md
> +All articles, blog posts, and videos I found mentioned either the solutions above or similar solutions. Each and everything I tried didn't show any progress during the compilation of the application.
- Each and everything I tried ... -> Everything I tried ...
- ..slack post for guidance up until I decided -> ..slack post for guidance *until* I decided

2022-09-05 14:20 UTC, mile95 requested changes
Snyggt jobbat Ömer!  Bra post! 

Lite som behöver korrigeras bara! Se kommentarer. 

I övrigt jag rekommendera två grejer.

1. Skriv en mening per rad i markdown, det brukar hjälpa folk att skriva bättre. Det gör det enklare att reviewa också. Det kommer inte bli ett nytt stycke med enkelrad :)
2. Släng in texten i grammarly när du är klar, det gör jag på allt jag skriver på engelska.  https://app.grammarly.com/ . Gratisversionen visar tydliga fel som man lätt gör. Säg till om du vill att jag ska visa hur den fungerar.

2022-09-05 14:20 UTC, mile95 commented on content/posts/2022-09-01_how-xcode-bamboozled-me.md
> +  - Devie Deviesson
Ömer Simsek!

2022-09-05 14:20 UTC, mile95 commented on content/posts/2022-09-01_how-xcode-bamboozled-me.md
> +tags: []
Lägg gärna till lite taggar

2022-09-05 14:20 UTC, mile95 commented on content/posts/2022-09-01_how-xcode-bamboozled-me.md
> +It's ten o'clock in the morning and I've just configurated and bumped the dependencies for my client's android application which they hadn't touched for over two years. Everything looked decent and w
article => post?

2022-09-05 14:20 UTC, mile95 commented on content/posts/2022-09-01_how-xcode-bamboozled-me.md
> +Reading this, my first instinct was to search this up on the good old browser. I felt safe and relieved reading posts and threads about other developers who also had gotten the same error message thi
..."using the goold old browser"?

2022-09-05 14:20 UTC, mile95 commented on content/posts/2022-09-01_how-xcode-bamboozled-me.md
> +Reading this, my first instinct was to search this up on the good old browser. I felt safe and relieved reading posts and threads about other developers who also had gotten the same error message thi
Det hade varit najs om du beskrev vad problemet faktiskt var innan lösningsalternativ tas upp. Typ vad syftar `Command PhaseScriptExecution failed with a nonzero exit code.` faktiskt på?

2022-09-05 14:20 UTC, mile95 commented on content/posts/2022-09-01_how-xcode-bamboozled-me.md
> +It was right there I realized that I did not only go too deep for a solution but I also got bamboozled by Xcode. The issue was never in the library dependency manager or using KeyChain access, rather
Här tappar du bort mig lite tyvärr. 

Här kommer helt nya loggar fram som inte presenterats innan. Innan du presenterar dessa loggarna kan det nog vara bra hur du gick från 

`Command PhaseScriptExecution failed with a nonzero exit code.`

till:

`AttributeError: 'dict' object has no attribute 'iteritems'
dict_items object has no attribute 'sort'`

Jag förstår att det är pga Apples developer men förtydliga gärna hur du hittade de nya loggarna.

2022-09-05 14:20 UTC, mile95 commented on content/posts/2022-09-01_how-xcode-bamboozled-me.md
> +If you're not a python enthusiast this won't say much rather than that there is no method `iteritems()` and `sort()`, and as someone that has done some python coding, `iteritems()` and `sort()` are m
suggestion: "... are methods existing in Python2 , but has been removed in Python3 ... "

2022-09-05 14:20 UTC, mile95 commented on content/posts/2022-09-01_how-xcode-bamboozled-me.md
> +If you're not a python enthusiast this won't say much rather than that there is no method `iteritems()` and `sort()`, and as someone that has done some python coding, `iteritems()` and `sort()` are m
Var det verkligen Xcode som använde sig av Python2 eller var det själva byggscriptet som inte hade satt python version?

Jag har inte suttit med XCode med jag vet att en klasssiker är att man i sina byggscript skriver typ: 

`python x.py` men om du på din maskin har python3 installerat men inte python2 så kan `python x.py` köras av `python3`. Man brukar därför skriva `python3 x.py" för att vara säker. 

Det här kan vara orelaterat men jag har sett XCode som en IDE och då känns det som att det snarare var fel på byggskriptet och inte XCode.

2022-09-05 14:20 UTC, mile95 commented on content/posts/2022-09-01_how-xcode-bamboozled-me.md
> +To solve my issue, I changed `sort()`to the new corresponding method`sorted()` and same with `ìteritems()` with `items()` on the custom script used during the compilation of my application.
Lägg till spaces innan code block

2022-09-05 15:04 UTC, omersimsek29 commented on content/posts/2022-09-01_how-xcode-bamboozled-me.md
> +If you're not a python enthusiast this won't say much rather than that there is no method `iteritems()` and `sort()`, and as someone that has done some python coding, `iteritems()` and `sort()` are m
Byggscripten är baserat på python 2.7, nackdelen här är att Apple depricate'a python 2.7 eftersom att 2.7 inte får support längre vilket är ett säkerhetsbrist. Använder man en äldre version av macOS så får man varningar men fr.om macOS 12.3 så ger det kompileringsfel. [Länk om python 2.7 & Apple](https://www.hexnode.com/blogs/apple-removing-python-2-7-on-mac-what-does-this-mean-for-it-admins/)

2022-09-06 08:05 UTC, omersimsek29 commented on content/posts/2022-09-01_how-xcode-bamboozled-me.md
> +It's ten o'clock in the morning and I've just configurated and bumped the dependencies for my client's android application which they hadn't touched for over two years. Everything looked decent and w
Uppdaterat!

2022-09-06 08:05 UTC, omersimsek29 commented on content/posts/2022-09-01_how-xcode-bamboozled-me.md
> +Reading this, my first instinct was to search this up on the good old browser. I felt safe and relieved reading posts and threads about other developers who also had gotten the same error message thi
Uppdaterat!

2022-09-06 08:06 UTC, omersimsek29 commented on content/posts/2022-09-01_how-xcode-bamboozled-me.md
> +- Suggests that you remove files such as Podfile.lock, the workspace file, and the Pod folder so that you reinstall them and do a clean folder build before compiling the application.
Uppdaterat! 😙

2022-09-06 08:06 UTC, omersimsek29 commented on content/posts/2022-09-01_how-xcode-bamboozled-me.md
> +All articles, blog posts, and videos I found mentioned either the solutions above or similar solutions. Each and everything I tried didn't show any progress during the compilation of the application.
Uppdaterat!

2022-09-06 08:06 UTC, omersimsek29 commented on content/posts/2022-09-01_how-xcode-bamboozled-me.md
> +If you're not a python enthusiast this won't say much rather than that there is no method `iteritems()` and `sort()`, and as someone that has done some python coding, `iteritems()` and `sort()` are m
Uppdaterat!

2022-09-06 08:06 UTC, omersimsek29 commented on content/posts/2022-09-01_how-xcode-bamboozled-me.md
> +To solve my issue, I changed `sort()`to the new corresponding method`sorted()` and same with `ìteritems()` with `items()` on the custom script used during the compilation of my application.
Tack, uppdaterat!

2022-09-06 08:06 UTC, omersimsek29 commented on content/posts/2022-09-01_how-xcode-bamboozled-me.md
> +  - Devie Deviesson
Juste... Uppdaterat!

2022-09-06 08:07 UTC, omersimsek29 commented on content/posts/2022-09-01_how-xcode-bamboozled-me.md
> +tags: []
Absolut, uppdaterat!

2022-09-06 08:07 UTC, omersimsek29 commented on content/posts/2022-09-01_how-xcode-bamboozled-me.md
> +It's ten o'clock in the morning and I've just configurated and bumped the dependencies for my client's android application which they hadn't touched for over two years. Everything looked decent and w
Sant, uppdaterat!

2022-09-06 08:07 UTC, omersimsek29 commented on content/posts/2022-09-01_how-xcode-bamboozled-me.md
> +Reading this, my first instinct was to search this up on the good old browser. I felt safe and relieved reading posts and threads about other developers who also had gotten the same error message thi
Old draft, borde inte ha skrivit sådär. Uppdaterat!

2022-09-06 08:09 UTC, omersimsek29 commented on content/posts/2022-09-01_how-xcode-bamboozled-me.md
> +It was right there I realized that I did not only go too deep for a solution but I also got bamboozled by Xcode. The issue was never in the library dependency manager or using KeyChain access, rather
Absolut, uppdaterat

2022-09-07 10:38 UTC, Dunklas commented
Grymt Ömer! Gillar hur du skrivit det som en berättelse, ungefär som er tidigare post om "We Got Cached".
Bra key learnings!

2022-09-07 10:38 UTC, Dunklas approved these changes

2022-09-07 19:58 UTC, mile95 approved these changes

2022-09-09 07:48 UTC, BunnyFiscuit approved these changes

2022-09-09 07:54 UTC, merged